name: Scheduled Merge Remote Action
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # pin@v3.0.0
        with:
          ref: master
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@f319e34ccad113d4f524e9ca33f5dab14b51117c # pin@v1.1.0
        with:
          upstream: MultiMC/meta-multimc
          upstream-branch: master
          branch: master
